### ISSUE TITLE
plz update installation command

### ISSUE THREAD

**Issue by Gary-Chow** [tadatoshi/photovoltaic_modeling_python#1]
Dear tadatoshi,

Thank you very much for your great work. It is helpful.

But I use the command "pip3 install photovoltaic-modeling-python", instead of "pip3 install photovoltaic_modeling" in README.md. The latter one runs across error.

Please update the installation command in README.md. If my mistake operation on your command leading to the error, plz let me know. 

Again, thx for your work!

Gary

**Comment by tadatoshi** [comment]
Dear Gary, 

I sincerely apologize that I was not able to look into this issue earlier. 

Thank you for finding the error in README.md. 
I tried the command and you are right. 
The command I wrote in README.md was incorrect and the command you are using is the correct one. 
I have corrected the installation command in the README.md. 

By the way, I am very glad to know that this project has been helpful to you. 

Sincerely, 
Tadatoshi
